// A small subset of words for demonstration purposes.
// In a real application, these would be fetched from an API.

export const VALID_GUESSES = [
  'cigar', 'rebut', 'sissy', 'humph', 'awake', 'blush', 'focal',
  'evade', 'naval', 'serve', 'hefty', 'magic', 'react', 'daily',
  'world', 'guess', 'spiel', 'sound', 'block', 'plane', 'style',
  'board', 'grape', 'music', 'plays', 'wordy', 'toast', 'email',
  'stone', 'crane', 'audio', 'plate', 'brave', 'adieu', 'arise',
  'which', 'there', 'their', 'about', 'would', 'these', 'other',
  'words', 'could', 'write', 'first', 'water', 'after', 'where',
  'right', 'think', 'three', 'years', 'place', 'great',
  'again', 'still', 'every', 'small', 'found', 'those', 'never',
  'under', 'might', 'while', 'house', 'below', 'asked',
  'going', 'large', 'until', 'along', 'shall', 'being', 'often',
  'earth', 'began', 'since', 'study', 'night', 'light', 'above',
  'paper', 'parts', 'young', 'story', 'point', 'times', 'heard',
  'whole', 'white', 'given', 'means', 'miles', 'thing',
  'today', 'later', 'using', 'money', 'lines', 'order', 'group',
  'among', 'learn', 'space', 'table', 'early', 'trees', 'short',
  'hands', 'state', 'black', 'shown', 'stood', 'front', 'voice',
  'kinds', 'makes', 'comes', 'close', 'power', 'lived', 'vowel',
  'taken', 'built', 'heart', 'ready', 'quite', 'class', 'bring',
  'round', 'horse', 'shows', 'piece', 'green', 'stand', 'birds',
  'start', 'river', 'tried', 'least', 'field', 'whose', 'girls',
  'leave', 'added', 'color', 'third', 'hours', 'moved', 'plant',
  'doing', 'names', 'forms', 'heavy', 'ideas', 'cried', 'check',
  'floor', 'begin', 'woman', 'alone', 'spell', 'watch',
  'carry', 'wrote', 'clear', 'named', 'books', 'child', 'glass',
  'human', 'takes', 'party', 'build', 'seems', 'blood', 'sides',
  'seven', 'mouth', 'solve', 'north', 'value', 'death', 'maybe',
  'happy', 'tells', 'gives', 'looks', 'shape', 'lives', 'steps',
  'areas', 'sense', 'speak', 'force', 'ocean', 'speed', 'women',
  'metal', 'south', 'grass', 'scale', 'cells', 'lower', 'sleep',
  'wrong', 'pages', 'ships', 'needs', 'rocks', 'eight', 'major',
  'level', 'total', 'ahead', 'reach', 'stars', 'store', 'sight',
  'terms', 'catch', 'works', 'cover', 'songs', 'equal',
  'waves', 'dance', 'spoke', 'break', 'cause',
  'radio', 'weeks', 'lands', 'basic', 'liked', 'trade', 'fresh',
  'final', 'fight', 'meant', 'drive', 'spent', 'local', 'waxes',
  'knows', 'train', 'bread', 'homes', 'teeth', 'coast', 'thick',
  'brown', 'clean', 'quiet', 'sugar', 'facts', 'steel', 'forth',
  'rules', 'notes', 'units', 'peace', 'month', 'verbs', 'seeds',
  'helps', 'sharp', 'visit', 'woods', 'chief', 'walls', 'wings',
  'grown', 'smile', 'string', 'youth', 'cream', 'laugh', 'graph',
  'doubt', 'brief', 'alarm', 'dirty', 'chart', 'stuck', 'dream',
  'gnome', 'sushi', 'spend', 'climb', 'brink',
  'abide', 'jumbo', 'quirk', 'fable', 'gleam', 'prize'
];

export const SOLUTIONS = [
  'react', 'style', 'board', 'grape', 'music', 'world', 'plane',
  'daily', 'wordy', 'plays', 'cigar', 'magic', 'toast', 'crane',
  'audio', 'brave', 'arise', 'adieu', 'stone', 'sound',
];
